### ISSUE TITLE
请问win可以部署吗？

### ISSUE THREAD

**Issue by wardenlzr** [ibisheng/onlyoffice-ibisheng#2]
看了一下你们的官方文档，似乎没有看到win 上面的使用部署文档

**Comment by lencil** [comment]
可以支持，仅限商业版，请电话咨询商业版。

lencil

**Comment by xiehongan123** [comment]
需要支持docker的windows版本： windowserver2016以后的版本或者windows10



在 2021-02-18 09:04:33，"Warden" <notifications@github.com> 写道：

Closed #2.
